### ISSUE TITLE
Looking up a deactivated widget's ancestor is unsafe.

### ISSUE THREAD

**Issue by eliezerantonio** [eliezerantonio/flutter_carousel_intro#27]
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

line 379

**Comment by antonio-nicolau** [comment]
Could you provide more insight on how to reproduce this issue ?

**Comment by antonio-nicolau** [comment]
I was able to reproduce

**Comment by antonio-nicolau** [comment]
It's happening because it's trying to dispose the `pageViewController` using the `context` already removed from the widget three. One of possible solution (since we want to dispose the `PageViewController`) is to override the `dispose` method inside `SlideModel` and dispose the PageViewController there. Like this

```Dart
 @override
  void dispose() {
    pageViewController.dispose();
    super.dispose();
  }

```

**Comment by antonio-nicolau** [comment]
I created a pull request with the fix https://github.com/eliezerantonio/flutter_carousel_intro/pull/28

**Comment by eliezerantonio** [comment]
well done
